# How Do You Handle Exceptions With Try/Except/Finally In Python?
# Explain with coding snippets

'''
An Exception is an Event, which occurs during the execution of the program
It is also known as a run time error. When that error occurs, Python generates an exception during the execution and that can be handled, which avoids your program to interrup


ex:-

a = 5
b = 0
print(a/b)

'''
 